# Generated by Django 5.1.4 on 2026-04-27 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'merchants',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount_paise', models.BigIntegerField()),
                ('entry_type', models.CharField(choices=[('CREDIT', 'Customer payment credit'), ('DEBIT', 'Payout debit'), ('REFUND', 'Refund for failed payout')], max_length=16)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='merchants.merchant')),
            ],
            options={
                'db_table': 'ledger_entries',
                'indexes': [models.Index(fields=['merchant', '-created_at'], name='ledger_entr_merchan_68130b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_paise', 0), _negated=True), name='ledger_amount_nonzero'), models.CheckConstraint(condition=models.Q(models.Q(('entry_type', 'CREDIT'), ('amount_paise__gt', 0)), models.Q(('entry_type', 'REFUND'), ('amount_paise__gt', 0)), models.Q(('entry_type', 'DEBIT'), ('amount_paise__lt', 0)), _connector='OR'), name='ledger_sign_matches_type')],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('holder_name', models.CharField(max_length=200)),
                ('account_number_last4', models.CharField(max_length=4)),
                ('ifsc', models.CharField(max_length=11)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='merchants.merchant')),
            ],
            options={
                'db_table': 'bank_accounts',
                'indexes': [models.Index(fields=['merchant', 'is_default'], name='bank_accoun_merchan_0abf24_idx')],
            },
        ),
    ]
