# Generated by Django 5.1.4 on 2026-04-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idempotencykey',
            name='status',
        ),
    ]
